version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8082:8082"
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3307"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
